### ISSUE TITLE
error on launch

### ISSUE THREAD

**Issue by GitZurah** [Mikooboy/csgo-chat-bot#2]
![image](https://user-images.githubusercontent.com/60843536/195248636-5b123f61-2cd9-4d22-9cf7-ee8a6cf02c24.png)
getting this error when the bot is running and i open cs. i swapped out 'csgo.exe' for 'csgo.sh' in cscb.py since i am running on linux, however this error is likely related to something else that i am sadly unable to figure out myself.

**Comment by Mikooboy** [comment]
Does the same problem occur if you let csgo start before running the bot?

**Comment by GitZurah** [comment]
yes

**Comment by GitZurah** [comment]
while i've gotten it to run now (kind of), the game crashes as soon as i load into a map while the chatbot is active in the background

sh: 1: cls: not found
Waiting for csgo to start... 
Trying 127.0.0.1:2121...
Successfully Connected!
sh: 1: cls: not found
Listening for commands from console...
Traceback (most recent call last):
  File "/home/linda/.tools/csgo-chat-bot/cscb.py", line 352, in <module>
    main()
  File "/home/linda/.tools/csgo-chat-bot/cscb.py", line 168, in main
    result = tn.expect([b"!calc\r\n", b"!help\r\n", b"!info\r\n", b"\* !info \r\n", b"!swquote\r\n", b" connected.", b"!bot", b"!clan", b"!clear"])
  File "/usr/lib/python3.10/telnetlib.py", line 637, in expect
    text = self.read_very_lazy()
  File "/usr/lib/python3.10/telnetlib.py", line 405, in read_very_lazy
    raise EOFError('telnet connection closed')
EOFError: telnet connection closed

**Comment by Mikooboy** [comment]
Something is causing the telnet connection to drop and I'm not sure what it is.

You can try the newer version here: https://github.com/Mikooboy/csgo-chat-bot_2.0
